### ISSUE TITLE
implement app signing in circle ci workflow to prevent warning on first install

### ISSUE THREAD

**Issue by grantdfoster** [voyansi/package-manager#21]
![image](https://user-images.githubusercontent.com/18288572/99696077-22cd7e00-2a43-11eb-8197-9e6ec39daa01.png)
![image](https://user-images.githubusercontent.com/18288572/99696090-27923200-2a43-11eb-8da0-c64003e677ac.png)

**Comment by mpothier** [comment]
Implemented code signing within CircleCI workflow with PR #82 .
While the installer .exe is now signed, note that the Window Defender pop up will still show until the app has built up enough "reputation" through user installs (https://security.stackexchange.com/questions/139347/smart-screen-filter-still-complains-despite-i-signed-the-executable-why)
